name: testdoc
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.9
    - pytest
    - sphinx
    - pip
    - matplotlib
    - mdutils
    - pip:
        - myst_parser
        - nbsphinx
